### ISSUE TITLE
TypeError in processRequest() with AWS lambda

### ISSUE THREAD

**Issue by pgeimer** [flash-oss/graphql-upload-minimal#4]
When I use ``processRequest`` in my AWS lambda function like this:
````
module.exports.hello = (event, context, callback) => {
    processRequest(event, null, { environment: "lambda" }).then((processed) => {
        // ...
    });
};
````
I get the following error:
````
ERROR	Unhandled Promise Rejection 	
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "TypeError: Cannot read property 'once' of null",
    "reason": {
        "errorType": "TypeError",
        "errorMessage": "Cannot read property 'once' of null",
        "stack": [
            "TypeError: Cannot read property 'once' of null",
            "    at /var/task/node_modules/graphql-upload-minimal/public/process-request.js:378:14",
            "    at new Promise (<anonymous>)",
            "    at processRequest (/var/task/node_modules/graphql-upload-minimal/public/process-request.js:78:10)",
            "    at Runtime.module.exports.handle [as handler] (/var/task/handler.js:27:9)",
            "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: TypeError: Cannot read property 'once' of null",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:310:20)",
        "    at process.EventEmitter.emit (domain.js:482:12)",
        "    at processPromiseRejections (internal/process/promises.js:209:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
    ]
}
````

**Comment by koresar** [comment]
Are you using the `graphql-upload-minimal@next` or the current stable?

**Comment by koresar** [comment]
Probably the README should be updated that it is showing the `@next` features. Sorry about the confusion.

**Comment by pgeimer** [comment]
I was using the current stable. With ``graphql-upload-minimal@next`` it worked. Thank you!

**Comment by koresar** [comment]
I was waiting for you! 
I'm going to publish it as stable. 😃

**Comment by koresar** [comment]
The new stable v1.2.0 was just published. No any changes comparing to the `@next` version.
Thanks again!
